version: '3'

services:
  nginx:
    build: 
      context: ./nginx-ssl/
      dockerfile: Dockerfile
    depends_on:
      - flask
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  flask:
    build: 
      context: ./uwsgi-flask/
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      -  ./uwsgi-flask/.env
    volumes:
      - ./uwsgi-flask/notes_app:/var/www/app
      - ./uwsgi-flask/notes_app/static:/usr/share/nginx/html

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_pass
      - POSTGRES_DB=p_db

volumes:
  postgres_data:



